In [1]:
import pandas as pd

In [2]:
# Read the Excel file as a DataFrame
df_full = pd.read_excel("survey.xlsx")
print("Num rows:", len(df_full))
df_full.head()

Num rows: 45

,StartDate,EndDate,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,...,Q10_38,Q10_39,Q10_40,Q10_41,Q10_42,Q10_43,Q10_44,Q10_45,Group,Device
0,Start Date,End Date,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Group,Device
1,2024-09-27 16:31:46,2024-09-27 16:38:46,100,419,True,2024-09-27 16:38:47.576000,R_3n3jcxk5gzQUj51,NaN,NaN,NaN,...,Agree,Somewhat agree,Agree,Agree,Somewhat agree,Somewhat disagree,Somewhat disagree,Agree,1,HCILab1
2,2024-09-30 14:44:13,2024-10-02 18:53:38,100,187764,True,2024-10-02 18:53:38.769000,R_1PgOiW6dxGDgBwB,NaN,NaN,NaN,...,Somewhat disagree,Agree,Somewhat agree,Strongly disagree,Somewhat agree,Somewhat disagree,Somewhat agree,Agree,1,HCILab2
3,2024-10-03 09:55:54,2024-10-03 19:07:42,100,33108,True,2024-10-03 19:07:43.679000,R_865YxVqKosNjcdf,NaN,NaN,NaN,...,Somewhat agree,Agree,Somewhat agree,Somewhat agree,Agree,Disagree,Disagree,Somewhat agree,1,CSL_LabPC
4,2024-10-04 02:04:21,2024-10-04 02:12:58,100,517,True,2024-10-04 02:12:59.827000,R_85MTBgBEA0MfUhb,NaN,NaN,NaN,...,Disagree,Somewhat agree,Somewhat disagree,Disagree,Disagree,Disagree,Disagree,Somewhat disagree,1,CSL_Laptop

In [4]:
# Filter the DataFrame to only include rows where the "Finished" column is "True"
df_scores = df_full[df_full["Finished"] == "True"].copy()
print("Num rows:", len(df_scores))

rating_map = {
    "Strongly disagree": 1,
    "Disagree": 2,
    "Somewhat disagree": 3,
    "Somewhat agree": 4,
    "Agree": 5,
    "Strongly agree": 6
}

# Convert text responses to numeric where applicable
for col in df_scores.columns:
    if col.startswith("Q10_"):
        df_scores.loc[:, col] = df_scores[col].map(rating_map)

df_scores.head()

Num rows: 41

,StartDate,EndDate,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,...,Q10_38,Q10_39,Q10_40,Q10_41,Q10_42,Q10_43,Q10_44,Q10_45,Group,Device
1,2024-09-27 16:31:46,2024-09-27 16:38:46,100,419,True,2024-09-27 16:38:47.576000,R_3n3jcxk5gzQUj51,NaN,NaN,NaN,...,5,4,5,5,4,3,3,5,1,HCILab1
2,2024-09-30 14:44:13,2024-10-02 18:53:38,100,187764,True,2024-10-02 18:53:38.769000,R_1PgOiW6dxGDgBwB,NaN,NaN,NaN,...,3,5,4,1,4,3,4,5,1,HCILab2
3,2024-10-03 09:55:54,2024-10-03 19:07:42,100,33108,True,2024-10-03 19:07:43.679000,R_865YxVqKosNjcdf,NaN,NaN,NaN,...,4,5,4,4,5,2,2,4,1,CSL_LabPC
4,2024-10-04 02:04:21,2024-10-04 02:12:58,100,517,True,2024-10-04 02:12:59.827000,R_85MTBgBEA0MfUhb,NaN,NaN,NaN,...,2,4,3,2,2,2,2,3,1,CSL_Laptop
5,2024-10-01 03:26:03,2024-10-01 03:33:58,100,474,True,2024-10-01 03:33:59.267000,R_5oZ7WckJpLcexwP,NaN,NaN,NaN,...,3,4,3,4,4,3,4,4,2,HCILab2

In [5]:
emotional_regulation_stages = {
    "Confront_Unpleasant_Situations": ["Q10_9", "Q10_11", "Q10_15", "Q10_28"],
    "Avoid_Unpleasant_Situations":    ["Q10_4", "Q10_5", "Q10_12", "Q10_18", "Q10_42", "Q10_44"],
    "Resolve_Conflicts":              ["Q10_6", "Q10_17", "Q10_19", "Q10_26", "Q10_36", "Q10_39"],
    "Avoid_Conflicts":                ["Q10_3", "Q10_10", "Q10_14", "Q10_37", "Q10_43"],
    "Focus_Elsewhere":                ["Q10_2", "Q10_22", "Q10_23", "Q10_31"],
    "Cognitively_Distract":           ["Q10_13", "Q10_27", "Q10_29", "Q10_33", "Q10_35"],
    "Consider_Benefits":              ["Q10_7", "Q10_20", "Q10_21", "Q10_24", "Q10_40", "Q10_45"],
    "Reduce_Importance":              ["Q10_25", "Q10_38", "Q10_41"],
    "Support_by_Emotion_Sharing":     ["Q10_8", "Q10_30", "Q10_32"],
    "Expressive_Suppression":         ["Q10_1", "Q10_16", "Q10_34"]
}

# Calculate the mean for each emotional regulation stage
for emotional_stage, questions in emotional_regulation_stages.items():
    df_scores[emotional_stage] = df_scores[questions].mean(axis=1, skipna=True)
    
df_scores.head()

,StartDate,EndDate,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,...,Confront_Unpleasant_Situations,Avoid_Unpleasant_Situations,Resolve_Conflicts,Avoid_Conflicts,Focus_Elsewhere,Cognitively_Distract,Consider_Benefits,Reduce_Importance,Support_by_Emotion_Sharing,Expressive_Suppression
1,2024-09-27 16:31:46,2024-09-27 16:38:46,100,419,True,2024-09-27 16:38:47.576000,R_3n3jcxk5gzQUj51,NaN,NaN,NaN,...,3.0,4.166667,3.833333,3.4,2.5,4.0,4.666667,5.0,4.666667,4.0
2,2024-09-30 14:44:13,2024-10-02 18:53:38,100,187764,True,2024-10-02 18:53:38.769000,R_1PgOiW6dxGDgBwB,NaN,NaN,NaN,...,5.0,3.333333,4.666667,2.6,3.0,2.6,5.0,2.333333,2.666667,3.333333
3,2024-10-03 09:55:54,2024-10-03 19:07:42,100,33108,True,2024-10-03 19:07:43.679000,R_865YxVqKosNjcdf,NaN,NaN,NaN,...,4.0,2.833333,4.333333,2.8,4.0,3.0,4.0,4.333333,4.333333,2.666667
4,2024-10-04 02:04:21,2024-10-04 02:12:58,100,517,True,2024-10-04 02:12:59.827000,R_85MTBgBEA0MfUhb,NaN,NaN,NaN,...,4.0,2.333333,4.166667,2.4,2.75,2.2,4.166667,2.666667,3.0,3.666667
5,2024-10-01 03:26:03,2024-10-01 03:33:58,100,474,True,2024-10-01 03:33:59.267000,R_5oZ7WckJpLcexwP,NaN,NaN,NaN,...,3.5,4.0,4.0,2.8,3.5,3.8,3.666667,4.0,4.666667,3.0

Build demographics table (44 rows, dashes for missing)

In [31]:
# Download the DataFrame as a CSV file
df_scores.to_csv("pmerq-survey-scores.csv", index=False)

In [38]:
# After reading df_full, drop that unwanted “extra” second row:
df_full = pd.read_excel("survey.xlsx")
df_full = df_full.reset_index(drop=True)
df_full = df_full.drop(df_full.index[0]).reset_index(drop=True)

demo_cols = {
    "ResponseId": "ParticipantID",
    "Q5":           "Age Range",
    "Q6":           "Gender",
    "Q7":           "Race",
    "Q8":           "Education",
    "Q9":           "Familiarity",
    "Group":        "Group",
    "Device":       "Device"
}

df_demo = df_full[list(demo_cols)].rename(columns=demo_cols)

# Clean the Familiarity text and only retain the first character
df_demo["Familiarity"] = df_demo["Familiarity"].astype(str).str[0]

# Collapse any “Other (please specify)” to just “Other”
df_demo["Race"] = (
    df_demo["Race"]
      .astype(str)
      .str.replace(r"(?i)^Other.*$", "Other", regex=True)
)

# Fill any NaN with dash
df_demo = df_demo.fillna("-")

# print("Participants in demo table:", len(df_demo) - 1)  # should be 43

latex = df_demo.to_latex(
    index=False,
    na_rep="-",            # simple hyphen
    caption="Participant demographics",
    label="tab:demographics",
    escape=True            # <— turn escaping back on
)

print(latex)

\begin{table}
\caption{Participant demographics}
\label{tab:demographics}
\begin{tabular}{llllllrl}
\toprule
ParticipantID & Age Range & Gender & Race & Education & Familiarity & Group & Device \\
\midrule
R\_3n3jcxk5gzQUj51 & 18-24 & Male & White & High school & 4 & 1 & HCILab1 \\
R\_1PgOiW6dxGDgBwB & 18-24 & Male & Asian & College & 3 & 1 & HCILab2 \\
R\_865YxVqKosNjcdf & 25-34 & Male & Asian & Professional degree & 2 & 1 & CSL\_LabPC \\
R\_85MTBgBEA0MfUhb & 18-24 & Male & Asian & Graduate degree & 2 & 1 & CSL\_Laptop \\
R\_5oZ7WckJpLcexwP & 18-24 & Male & Asian & Professional degree & 3 & 2 & HCILab2 \\
R\_6YuNtoM4ihsHh6h & 18-24 & Male & White & High school & 2 & 2 & HCILab1 \\
R\_207DqscZCOvzhaB & 25-34 & Female & White & Graduate degree & 2 & 2 & CSL\_LabPC \\
R\_2LGyH5rtoDSTN29 & 25-34 & Male & Asian & Professional degree & 2 & 2 & CSL\_Laptop \\
R\_7LTm1hYyDqLwvM5 & 18-24 & Male & Asian & Graduate degree & 2 & 3 & HCILab1 \\
R\_8S3BMvJviSME521 & 18-24 & Male & Asian & High school & 1 & 3 & CSL\_LabPC \\
R\_1hR6g7wETs7k8aA & 18-24 & Male & Asian & High school & 2 & 3 & HCILab2 \\
R\_2sotPCAUKSZ8SuB & 35-44 & Female & White & College & 3 & 3 & CSL\_Laptop \\
R\_839Koc4sOixUtjO & 18-24 & Female & White & College & 2 & 4 & CSL\_LabPC \\
R\_6ik7hlrS0Y6wamp & 18-24 & Male & White & College & 3 & 4 & HCILab1 \\
R\_8txHfvBvonMlmLD & 18-24 & Female & Other & High school & 3 & 4 & CSL\_Laptop \\
R\_3DuAH4I5dlX5Pxv & 18-24 & Female & Asian & Professional degree & 1 & 4 & HCILab2 \\
R\_2uqWof8LAqnbBQd & 25-34 & Female & Asian & Professional degree & 3 & 5 & CSL\_Laptop \\
R\_1nVEP2idiWV6k0x & 18-24 & Other & Asian & High school & 4 & 5 & HCILab2 \\
R\_5AFR45OgA1U7Tih & 18-24 & Male & Asian & Graduate degree & 4 & 5 & HCILab1 \\
R\_5ncoOJye2thvLQK & 18-24 & Male & Asian & College & 3 & 6 & HCILab1 \\
R\_2QEJbtknRWAFIna & 18-24 & Male & Asian & Graduate degree & 2 & 6 & CSL\_Laptop \\
R\_5QKHTvZXGsz88bv & 18-24 & Male & White & High school & 3 & 6 & HCILab2 \\
R\_2Dc1FaB5zQarntk & 25-34 & Female & Asian & Graduate degree & 1 & 6 & CSL\_LabPC \\
R\_8Jg7wrGzOSZI57r & 18-24 & Male & Asian & Graduate degree & 2 & 7 & CSL\_Laptop \\
R\_5rihp7tYxo4cikp & 18-24 & Male & White & High school & 3 & 7 & HCILab2 \\
R\_7jP5W4EZSbwjlhn & 25-34 & Male & Asian & College & 2 & 7 & HCILab1 \\
R\_29G09nTqHpkFC9P & 18-24 & Male & Other & Graduate degree & 2 & 7 & CSL\_LabPC \\
R\_8KT4VqDz3jREje3 & 18-24 & Female & White & High school & 3 & 8 & CSL\_Laptop \\
R\_7VjNhKtdoF3JX56 & 18-24 & Male & White & High school & 4 & 8 & HCILab1 \\
R\_1DqAAT2AQvj7Yud & 25-34 & Male & Asian & Professional degree & 2 & 8 & HCILab2 \\
R\_2q4kC691PjzpeDR & 18-24 & Female & Asian & College & 3 & 8 & CSL\_LabPC \\
R\_8aCU2B4nwcyUpEe & 18-24 & Female & Asian & Graduate degree & 1 & 9 & CSL\_Laptop \\
R\_5ypEl8FVl5gr6lB & 25-34 & Male & White & Graduate degree & 4 & 9 & HCILab1 \\
R\_7erfgegeIsghiN1 & 25-34 & Female & White & Graduate degree & 3 & 9 & HCILab2 \\
R\_5Gw9Ne3QojNMcSX & 25-34 & Male & Asian & Professional degree & 2 & 10 & HCILab2 \\
R\_8Evgc7CFeEcLGJY & 25-34 & Female & Asian & Professional degree & 1 & 10 & CSL\_Laptop \\
R\_3iBW6RrQRhkIDOo & 25-34 & Male & Asian & College & 2 & 10 & HCILab1 \\
R\_6dnyFUzMOE20p4e & 25-34 & Female & Other & Graduate degree & 2 & 11 & HCILab1 \\
R\_670Oc16oFsbEywp & 18-24 & Male & Asian & Graduate degree & 3 & 11 & HCILab2 \\
- & - & - & nan & - & 1 & 11 & CSL\_Laptop \\
R\_1wcarhM0eHMnWvf & 18-24 & Non-binary & White & High school & 3 & 12 & HCILab2 \\
R\_5nkICnyw7iLOBUL & 18-24 & Male & Other & High school & 3 & 12 & HCILab1 \\
R\_8oWQ4BjakEtaQOB & 25-34 & Female & White & College & 4 & 12 & CSL\_LabPC \\
- & - & - & nan & - & 2 & 12 & CSL\_Laptop \\
\bottomrule
\end{tabular}
\end{table}

/var/folders/h8/8z2sfwhs7jnb1_3vtp670q480000gn/T/ipykernel_37606/3732520284.py:30: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_demo = df_demo.fillna("-")

Overall summary stats (mean ± SD) for each emotional stage

In [36]:
# only on finished participants
raw = df_scores[list(emotional_regulation_stages)].agg(["mean", "std"]).T

# create the single formatted column
raw["Mean ± SD"] = raw.apply(
    lambda r: f"{r['mean']:.2f} \u00B1 {r['std']:.2f}", axis=1
)

# keep only that combined column
stats_single = raw[["Mean ± SD"]]

print(stats_single.to_latex(
    index=True,
    header=["Mean \\pm SD"],    # if you want to LaTeX-escape the ±
    escape=True,
    caption="Overall mean ± SD by emotional regulation stage"
))

\begin{table}
\caption{Overall mean ± SD by emotional regulation stage}
\begin{tabular}{ll}
\toprule
 & Mean \pm SD \\
\midrule
Confront\_Unpleasant\_Situations & 3.60 ± 1.05 \\
Avoid\_Unpleasant\_Situations & 4.17 ± 1.00 \\
Resolve\_Conflicts & 4.19 ± 0.59 \\
Avoid\_Conflicts & 3.76 ± 0.87 \\
Focus\_Elsewhere & 3.76 ± 0.90 \\
Cognitively\_Distract & 4.09 ± 0.96 \\
Consider\_Benefits & 4.24 ± 0.88 \\
Reduce\_Importance & 4.28 ± 0.85 \\
Support\_by\_Emotion\_Sharing & 3.99 ± 1.17 \\
Expressive\_Suppression & 3.94 ± 0.92 \\
\bottomrule
\end{tabular}
\end{table}

Group‑level summary (Groups 1–12)

In [28]:
# 1. Filter groups 1–12
df_g1_12 = df_scores[df_scores["Group"].astype(float).between(1, 12)]

# 2. Compute the raw means and stds
raw = (
    df_g1_12
    .groupby("Group")[list(emotional_regulation_stages)]
    .agg(["mean", "std"])
)

# 3. Build a new DataFrame where each stage is one column formatted as "M ± S"
grp_stats_single = pd.DataFrame(index=raw.index)
for stage in emotional_regulation_stages:
    mean_col = raw[(stage, "mean")]
    std_col  = raw[(stage, "std")]
    grp_stats_single[stage] = (
        mean_col.map("{:.2f}".format)
        + " ± "
        + std_col.map("{:.2f}".format)
    )

# 4. (Optionally rename columns for prettier labels)
grp_stats_single.columns = [stage.replace("_", " ") for stage in grp_stats_single.columns]

# 5. Export to LaTeX
print(grp_stats_single.to_latex(
    index=True,
    caption="Mean \\(\\pm\\) SD by group (1–12)",
    escape=False
))

\begin{table}
\caption{Mean \(\pm\) SD by group (1–12)}
\begin{tabular}{lllllllllll}
\toprule
 & Confront Unpleasant Situations & Avoid Unpleasant Situations & Resolve Conflicts & Avoid Conflicts & Focus Elsewhere & Cognitively Distract & Consider Benefits & Reduce Importance & Support by Emotion Sharing & Expressive Suppression \\
Group &  &  &  &  &  &  &  &  &  &  \\
\midrule
1 & 4.00 ± 0.82 & 3.17 ± 0.78 & 4.25 ± 0.35 & 2.80 ± 0.43 & 3.06 ± 0.66 & 2.95 ± 0.77 & 4.46 ± 0.46 & 3.58 ± 1.29 & 3.67 ± 0.98 & 3.42 ± 0.57 \\
2 & 3.58 ± 0.14 & 3.56 ± 1.07 & 3.50 ± 0.50 & 3.20 ± 0.87 & 3.50 ± 0.00 & 4.33 ± 0.76 & 3.50 ± 0.29 & 3.67 ± 0.33 & 4.56 ± 1.50 & 3.56 ± 0.51 \\
3 & 3.25 ± 1.37 & 4.62 ± 1.04 & 3.96 ± 0.50 & 4.50 ± 0.82 & 4.50 ± 0.98 & 4.70 ± 1.18 & 4.21 ± 0.93 & 4.92 ± 0.88 & 4.00 ± 1.41 & 4.42 ± 0.57 \\
4 & 3.56 ± 0.69 & 4.50 ± 0.41 & 4.38 ± 0.64 & 3.65 ± 0.34 & 3.94 ± 1.39 & 3.95 ± 0.66 & 4.71 ± 1.27 & 4.67 ± 0.82 & 3.92 ± 0.79 & 3.25 ± 1.23 \\
5 & 4.00 ± 1.00 & 4.39 ± 0.79 & 4.50 ± 0.87 & 3.40 ± 1.20 & 3.42 ± 1.38 & 4.60 ± 0.87 & 4.44 ± 0.48 & 4.67 ± 1.20 & 3.22 ± 1.84 & 4.56 ± 0.69 \\
6 & 4.69 ± 0.75 & 4.25 ± 0.62 & 4.42 ± 0.10 & 4.30 ± 0.35 & 4.44 ± 0.52 & 4.30 ± 0.38 & 4.54 ± 0.16 & 4.50 ± 0.58 & 4.92 ± 0.50 & 3.75 ± 0.69 \\
7 & 3.25 ± 1.17 & 4.88 ± 0.52 & 4.21 ± 0.53 & 4.35 ± 0.34 & 3.94 ± 0.94 & 4.35 ± 0.70 & 4.08 ± 0.73 & 4.67 ± 0.38 & 4.58 ± 1.13 & 4.33 ± 0.54 \\
8 & 3.25 ± 1.31 & 4.33 ± 1.53 & 4.42 ± 0.75 & 4.05 ± 1.00 & 3.06 ± 1.25 & 3.85 ± 1.28 & 4.17 ± 1.22 & 4.17 ± 0.64 & 3.33 ± 1.12 & 4.50 ± 0.69 \\
9 & 3.25 ± 1.25 & 3.94 ± 0.59 & 4.06 ± 1.23 & 4.60 ± 0.35 & 3.92 ± 0.63 & 3.93 ± 0.99 & 4.61 ± 0.35 & 4.56 ± 0.69 & 4.33 ± 1.67 & 3.67 ± 2.00 \\
10 & 3.67 ± 0.95 & 3.06 ± 0.98 & 4.33 ± 0.17 & 3.27 ± 0.12 & 3.58 ± 0.58 & 3.80 ± 0.87 & 4.50 ± 0.67 & 3.89 ± 0.51 & 4.67 ± 0.33 & 4.11 ± 0.69 \\
11 & 4.62 ± 0.88 & 3.92 ± 1.53 & 4.50 ± 0.24 & 2.30 ± 0.99 & 4.00 ± 0.35 & 3.20 ± 1.98 & 4.92 ± 0.59 & 3.83 ± 1.65 & 4.00 ± 0.00 & 3.83 ± 1.65 \\
12 & 2.33 ± 1.01 & 5.17 ± 0.73 & 3.72 ± 0.51 & 3.87 ± 0.46 & 3.67 ± 0.14 & 5.00 ± 0.20 & 2.67 ± 1.01 & 3.89 ± 0.77 & 2.56 ± 0.51 & 3.89 ± 1.17 \\
\bottomrule
\end{tabular}
\end{table}