In [1]:
import pandas as pd

In [33]:
# Read the Excel file as a DataFrame
df = pd.read_excel("survey.xlsx")
print("Num rows:", len(df))
df.head()

Num rows: 45

,StartDate,EndDate,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,...,Q10_38,Q10_39,Q10_40,Q10_41,Q10_42,Q10_43,Q10_44,Q10_45,Group,Device
0,Start Date,End Date,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Please rate your agreement with the following ...,Group,Device
1,2024-09-27 16:31:46,2024-09-27 16:38:46,100,419,True,2024-09-27 16:38:47.576000,R_3n3jcxk5gzQUj51,NaN,NaN,NaN,...,Agree,Somewhat agree,Agree,Agree,Somewhat agree,Somewhat disagree,Somewhat disagree,Agree,1,HCILab1
2,2024-09-30 14:44:13,2024-10-02 18:53:38,100,187764,True,2024-10-02 18:53:38.769000,R_1PgOiW6dxGDgBwB,NaN,NaN,NaN,...,Somewhat disagree,Agree,Somewhat agree,Strongly disagree,Somewhat agree,Somewhat disagree,Somewhat agree,Agree,1,HCILab2
3,2024-10-03 09:55:54,2024-10-03 19:07:42,100,33108,True,2024-10-03 19:07:43.679000,R_865YxVqKosNjcdf,NaN,NaN,NaN,...,Somewhat agree,Agree,Somewhat agree,Somewhat agree,Agree,Disagree,Disagree,Somewhat agree,1,CSL_LabPC
4,2024-10-04 02:04:21,2024-10-04 02:12:58,100,517,True,2024-10-04 02:12:59.827000,R_85MTBgBEA0MfUhb,NaN,NaN,NaN,...,Disagree,Somewhat agree,Somewhat disagree,Disagree,Disagree,Disagree,Disagree,Somewhat disagree,1,CSL_Laptop

In [38]:
# Filter the DataFrame to only include rows where the "Finished" column is "True"
df_finished = df[df["Finished"] == "True"].copy()
print("Num rows:", len(df_finished))

rating_map = {
    "Strongly disagree": 1,
    "Disagree": 2,
    "Somewhat disagree": 3,
    "Somewhat agree": 4,
    "Agree": 5,
    "Strongly agree": 6
}

# Convert text responses to numeric where applicable
for col in df_finished.columns:
    if col.startswith("Q10_"):
        df_finished.loc[:, col] = df_finished[col].map(rating_map)

df_finished.head()

Num rows: 41

,StartDate,EndDate,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,...,Q10_38,Q10_39,Q10_40,Q10_41,Q10_42,Q10_43,Q10_44,Q10_45,Group,Device
1,2024-09-27 16:31:46,2024-09-27 16:38:46,100,419,True,2024-09-27 16:38:47.576000,R_3n3jcxk5gzQUj51,NaN,NaN,NaN,...,5,4,5,5,4,3,3,5,1,HCILab1
2,2024-09-30 14:44:13,2024-10-02 18:53:38,100,187764,True,2024-10-02 18:53:38.769000,R_1PgOiW6dxGDgBwB,NaN,NaN,NaN,...,3,5,4,1,4,3,4,5,1,HCILab2
3,2024-10-03 09:55:54,2024-10-03 19:07:42,100,33108,True,2024-10-03 19:07:43.679000,R_865YxVqKosNjcdf,NaN,NaN,NaN,...,4,5,4,4,5,2,2,4,1,CSL_LabPC
4,2024-10-04 02:04:21,2024-10-04 02:12:58,100,517,True,2024-10-04 02:12:59.827000,R_85MTBgBEA0MfUhb,NaN,NaN,NaN,...,2,4,3,2,2,2,2,3,1,CSL_Laptop
5,2024-10-01 03:26:03,2024-10-01 03:33:58,100,474,True,2024-10-01 03:33:59.267000,R_5oZ7WckJpLcexwP,NaN,NaN,NaN,...,3,4,3,4,4,3,4,4,2,HCILab2

In [ ]:
emotional_regulation_stages = {
    "Confront_Unpleasant_Situations": ["Q10_9", "Q10_11", "Q10_15", "Q10_28"],
    "Avoid_Unpleasant_Situations":    ["Q10_4", "Q10_5", "Q10_12", "Q10_18", "Q10_42", "Q10_44"],
    "Resolve_Conflicts":              ["Q10_6", "Q10_17", "Q10_19", "Q10_26", "Q10_36", "Q10_39"],
    "Avoid_Conflicts":                ["Q10_3", "Q10_10", "Q10_14", "Q10_37", "Q10_43"],
    "Focus_Elsewhere":                ["Q10_2", "Q10_22", "Q10_23", "Q10_31"],
    "Cognitively_Distract":           ["Q10_13", "Q10_27", "Q10_29", "Q10_33", "Q10_35"],
    "Consider_Benefits":              ["Q10_7", "Q10_20", "Q10_21", "Q10_24", "Q10_40", "Q10_45"],
    "Reduce_Importance":              ["Q10_25", "Q10_38", "Q10_41"],
    "Support_by_Emotion_Sharing":     ["Q10_8", "Q10_30", "Q10_32"],
    "Expressive_Suppression":         ["Q10_1", "Q10_16", "Q10_34"]
}

# Calculate the mean for each emotional regulation stage
for emotional_stage, questions in emotional_regulation_stages.items():
    df_finished[emotional_stage] = df_finished[questions].mean(axis=1, skipna=True)
    
df_finished.head()

,StartDate,EndDate,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,...,Confront_Unpleasant_Situations,Avoid_Unpleasant_Situations,Resolve_Conflicts,Avoid_Conflicts,Focus_Elsewhere,Cognitively_Distract,Consider_Benefits,Reduce_Importance,Support_by_Emotion_Sharing,Expressive_Suppression
1,2024-09-27 16:31:46,2024-09-27 16:38:46,100,419,True,2024-09-27 16:38:47.576000,R_3n3jcxk5gzQUj51,NaN,NaN,NaN,...,3.0,4.166667,3.833333,3.4,2.5,4.0,4.666667,5.0,4.666667,4.0
2,2024-09-30 14:44:13,2024-10-02 18:53:38,100,187764,True,2024-10-02 18:53:38.769000,R_1PgOiW6dxGDgBwB,NaN,NaN,NaN,...,5.0,3.333333,4.666667,2.6,3.0,2.6,5.0,2.333333,2.666667,3.333333
3,2024-10-03 09:55:54,2024-10-03 19:07:42,100,33108,True,2024-10-03 19:07:43.679000,R_865YxVqKosNjcdf,NaN,NaN,NaN,...,4.0,2.833333,4.333333,2.8,4.0,3.0,4.0,4.333333,4.333333,2.666667
4,2024-10-04 02:04:21,2024-10-04 02:12:58,100,517,True,2024-10-04 02:12:59.827000,R_85MTBgBEA0MfUhb,NaN,NaN,NaN,...,4.0,2.333333,4.166667,2.4,2.75,2.2,4.166667,2.666667,3.0,3.666667
5,2024-10-01 03:26:03,2024-10-01 03:33:58,100,474,True,2024-10-01 03:33:59.267000,R_5oZ7WckJpLcexwP,NaN,NaN,NaN,...,3.5,4.0,4.0,2.8,3.5,3.8,3.666667,4.0,4.666667,3.0

In [41]:
# Download the DataFrame as a CSV file
df_finished.to_csv("pmerq-survey-scores.csv", index=False)